#!/bin/bash

# Compile the C code using gcc
gcc -o simple_shell simple_shell.c

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Compilation successful! Running './simple_shell'..."
    ./simple_shell
else
    echo "Compilation failed."
fi
